### Invoke Servidor
GET http://localhost:8080/
Accept: application/json

###
GET http://localhost:8080/profile
Accept: application/json

### Get all data
GET http://localhost:8080/country
Accept: application/json

### Get country by Id
GET http://localhost:8080/country/110
Accept: application/json

### Create new country
POST http://localhost:8080/country
Content-Type: application/json

{
    "country": "Tefisita"
}

### Update Country
PUT http://localhost:8080/country/111
Content-Type: application/json

{
    "country": "Software2"
}

### Delete Country
DELETE http://localhost:8080/country/110
Accept: application/json